###############################################################
#  Generated by:      Cadence Innovus 21.13-s100_1
#  OS:                Linux x86_64(Host ID acf3030)
#  Generated on:      Thu Oct 27 19:09:16 2022
#  Design:            b14
#  Command:           floorPlan -site FreePDK45_38x28_10R_NP_162NW_34O -r 1 0.5
###############################################################

(globals
    version = 3
    io_order = default
)
